### PR TITLE
#127 client implement traineesection

### PR DESCRIPTION
**Pull request by Prschmidt**
Created the table for internal projects, currently without API and created a grid for the members of the current trainee generation. Also prepared the grid for APIs, the code is currently outcommented

Please check, if table and grid is shown properly and for potential optimization of the code.
Also check, if checkboxes for IPs can be ticked, the filter function works and that the checkboxes for the trainees are disabled

How to test new version:
1. user without permission
- check if all ips are loaded
- check if all trainees for the respective ips are loaded
- check if you can switch between generations
- check if the ip detail page is linked, should navigate to /internes-projekt/:id (detail page is another issue #135 )
- check if the links to the trainee profile page is working
2. user with permission
- check if the button to add an ip is only for the most recent generation available
- check wether the errors/warnings pop up if you leave some fields blank when adding an ip
- check if the alert pops up after adding an ip
- check wether the table for the workshops is shown porperly

### CODE REVIEW

**Comment by arisb1470** [comment]
Looks good! As the backend isn't ready yet, there wasn't a way for me to check your code for the API implementation. For the table: While checks for "Angebot abgegeben" do appear to be working, the ones for the "ZP" and "AP" aren't showing. As for the grid: The Trainees are shown as buttons. That isn't the case for the old MDB. If that was intentional though, there are no complaints for me there.

**Comment by arisb1470** [comment]
Looks good! Some issues are still there though:

When loading the page for the first time, an error pops up that the authorization couldn't load.
image

There doesn't seem to be any Traineegeneration that is selected when loading the page, although the trainees from the current generation are shown.
image

A line goes straight through the trainee table. I don't know if that is there purposefully, it seems random though.
image

The table is quite wide, which means that you cannot see all categories without scrolling. I do understand however why that was chosen instead of the original design of the page, which is why that isn't a dealbreaker or anything as I can't think of any better fix for it myself.

Apart from those I couldn't find anything though :)

**Comment by arisb1470** [comment]
> Looks good! Some issues are still there though:
> 
> When loading the page for the first time, an error pops up that the authorization couldn't load. image
> 
> There doesn't seem to be any Traineegeneration that is selected when loading the page, although the trainees from the current generation are shown. image
> 
> A line goes straight through the trainee table. I don't know if that is there purposefully, it seems random though. image
> 
> The table is quite wide, which means that you cannot see all categories without scrolling. I do understand however why that was chosen instead of the original design of the page, which is why that isn't a dealbreaker or anything as I can't think of any better fix for it myself.
> 
> Apart from those I couldn't find anything though :)

**Comment by arisb1470** [comment]
For the line through the tabe: The issue seems to be that the map around the table is too small, the line being the right edge of the map. 

For the width of the table: You could use abbreviations to save space, adding a legend or unfolding the whole name when hovering above the categories.

**Comment by arisb1470** [comment]
For the line through the tabe: The issue seems to be that the map around the table is too small, the line being the right edge of the map.

For the width of the table: You could use abbreviations to save space, adding a legend or unfolding the whole name when hovering above the categories.

**Comment by Prschmidt** [comment]
Your Code looks good from my side.

**Comment by arisb1470** [comment]
The field around the (trainee-)table seems to have a static size, meaning that when you switch to the mobile version, there is an overlap like this: 
image
Other than that everything looks good!

**Review by arisb1470 — APPROVED** [review]

**Pull request merged**
